package-lock.json
public/index.html
src/App.js
src/components/shoppingCart/shoppingCart.jsx
src/components/shoppingCart/shoppingCart.module.css

Creacion modelo base shop. Checkbox y selected de filter.
Enrutado de app.
Importe Boostrap en public/index.

Creacion of components shop

---

src/components/loginComponents/loginComponents.jsx
src/components/registerComponents/registerComponents.jsx
src/views/login/index.jsx
src/views/register/index.jsx

Login and register components created

Added the Login/Register components folder and drivers

---

src/components/shoppingCart/shoppingCart.jsx
src/components/shoppingCart/shoppingCart.module.css
src/components/shoppingCart/typesAndColors.jsx
src/img/img.jsx

I add img folder with hardcoded templates.
Images obtained from cloudinary
Added type and color file for cleaner code.
I render types and colors with map.
css fix

advance shop and template

---

package-lock.json
package.json
postcss.config.js
src/App.js
src/Redux/actions.js
src/components/Cart/cart.jsx
src/index.js
src/styles/input.css
src/styles/output.css
src/views/cart.jsx
tailwind.config.js

I'll be working during night on these so i'll merge it later

Feature/ Cart in folder views

---

src/components/shoppingCart/Filter.jsx
src/components/shoppingCart/Order.jsx
src/components/shoppingCart/Plantillas.jsx
src/components/shoppingCart/shoppingCart.jsx
src/components/shoppingCart/shoppingCart.module.css

I add modules for rendering order, filters and templates.
Link of the shop with Redux in their respective arrangements and filters, it remains to finish connecting them correctly for their operation

Modularization of shop and connection with redux

---

public/index.html
src/components/Nav/Nav.jsx

Add in Nav.jsx Navlinks to Routes

Add(components/Nav/Nav.jsx) Add NavLinks to Routes

---

src/components/Footer/Footer.jsx
src/views/home/HomeViews.jsx

Footer component created and added to home.jsx

Footer component created and added to home.jsx

---

src/components/Banner/Banner.jsx
src/components/Banner/banner.module.css

actualization of banner.jsx style

fix(components/Banner.jsx) actualization of banner.jsx style

---

src/components/Cart/cart.jsx
src/components/Nav/Nav.jsx
src/styles/output.css
tailwind.config.js

Configuration of tailwind and funcitons on Cart component

configuration of tailwind and modifing cart component

---

src/Redux/actions.js

Now Redux is completed from the side of the user state and we are waiting for the server team to finish the request

deleted some actions of Redux and finish Redux for User State

---

src/components/registerComponents/registerComponents.jsx
src/components/validation.js

completed de validations for register component and modularized it

completed de validations for register component and modularized it

---

src/components/Nav/Nav.jsx

Added Sign In and Profile to Nav bar, so we can have better and understandable users seccions.

Added Sign In and Profile to Nav Bar

---

src/components/registerComponents/registerComponents.jsx

Styles added to Register component

Register form styles added

---

src/components/Footer/Footer.jsx

Social media urls added

---

src/components/Footer/Footer.jsx

Added shop route to Shop´s Link

Added shop route to Shop´s Link

---

src/components/Nav/Nav.jsx

fix(components/nav.jsx) fix button actions

---

src/Redux/actions.js
src/Redux/reducer.js
src/Redux/types.js
src/components/Nav/Nav.jsx

add logOut function in Nav.jsx and redux

fix(nav.jsx & redux) add LogOut

---

src/components/Banner/Banner.jsx

fix(components/banner.jsx) fix banner color

---

src/App.js
src/Redux/actions.js
src/components/loginComponents/loginComponents.jsx
src/components/registerComponents/registerComponents.jsx

- App modification when the state is updated with the stored user.
- Added password verification view to the register component

Update state with stored user

---

src/components/registerComponents/registerComponents.jsx

Added link to go back Home to the component

Added link to go back Home to the component

---

src/components/loginComponents/loginComponents.jsx

Added link back to home to the Login component

Added link back to home to the Login component

---

src/components/Footer/Footer.jsx
src/components/Nav/Nav.jsx
src/components/registerComponents/registerComponents.jsx

i removed the class mt from every component on the nav bar and now its all center

aligning items in nav component

---

src/App.js
src/Redux/actions.js
src/Redux/reducer.js
src/Redux/types.js
src/components/shoppingCart/shoppingCart.jsx

functionality fixes in database loading and duplicate filtering

functionality fixes

---

src/components/Cart/cart.jsx

Styles added to Cart component

Styles added to Cart component

---

src/components/shoppingCart/ComponentShop.jsx
src/components/shoppingCart/Order.jsx
src/components/shoppingCart/Plantillas.jsx
src/components/shoppingCart/shoppingCart.jsx

fix(components/shoppingCart) fix styles

---

src/components/shoppingCart/Plantillas.jsx

Changed text color to the cards

Changed text color to the cards

---

src/Redux/actions.js
src/Redux/reducer.js
src/components/Cart/cart.jsx
src/components/shoppingCart/Plantillas.jsx
src/utils/img/ulisesPresets.json

Now we have a buy button in every preset and it add's to the cart the preset after a request from the server, still have to do the local storage in order to keep seeing it when you go to the cart component

adapted Redux functions to fill the cart

---

src/components/Nav/Nav.jsx

only change button of logout colors

fix(nav.jsx) change button LogOut colors

---

src/App.js
src/components/Detail/Detail.jsx
src/views/detail/detail.jsx

Created Detail component and view. Added a new route to App.js

Detail component

---

src/components/shoppingCart/ComponentShop.jsx
src/components/shoppingCart/Order.jsx

Added a clear filters and sorting button

add button clearFilter

---

src/components/Detail/Detail.jsx
src/components/shoppingCart/Plantillas.jsx

New functions and route correction for detail.

feature detail

---

src/components/shoppingCart/ComponentShop.jsx
src/components/shoppingCart/Plantillas.jsx
src/components/shoppingCart/typesAndColors.jsx

I add the filter by types and combine it with the other filters.
I reinforced the requests to the back for a clearer and more functional code.

add filterType and fix gets in shop

---

src/components/Detail/Detail.jsx
src/components/shoppingCart/Plantillas.jsx

Added link to detail to preset´s name and properties on detail´s component

Detail component changes

---

src/utils/img/templates_exemples/template_01.jsx

create a template for templating with comments on how it works

features(utils/template_examples/template_01.jsx) create template

---

src/Redux/actions.js
src/components/Profile/Profile.jsx

fix(profile.jsx & action.js) fix localstorage set user

---

public/index.html
src/components/PresetsDesigns/Basic/About/BasicAbout01.jsx

feature(PresetsDesigns/Basic) create about  presets design

---

src/Redux/actions.js
src/Redux/reducer.js
src/Redux/types.js
src/components/Pay/payComponent.jsx

added basic functions to pay component and redux changes por deployment status

pay component

---

src/App.js

In case that the token is invalid or expired, it would be remover of the localStorage

feat(app/localStorage): added remove of token

---

src/components/Cart/cart.jsx

fix(cart.jsx) fix cart styles

---

src/components/Detail/Detail.jsx
src/components/shoppingCart/Plantillas.jsx

Fixed shoppingCart component. Link to detail is already  working

Fixed ShoppingCart component

---

src/App.js
src/Redux/actions.js
src/components/Nav/Nav.jsx
src/components/Profile/Profile.jsx
src/components/loginComponents/loginComponents.jsx
src/index.js

src/App.js
Removed / commented unnecessary code
Formatted all files
src/Redux/actions.js
Removed action to save the user token since it now saves at the localStorage
src/components/Nav/Nav.jsx
Added logout method from auth0 to avoid issues while logging off
src/components/Profile/Profile.jsx
Data persists after reloading the website
src/components/loginComponents/loginComponents.jsx
Added functionality for auth0
src/index.js
Added auth0 provider
P.S: Right now all data from a user logged in with auth0 is lost on reload, the only way to avoid this is to logout and re-login

feature(auth0): added auth0

---

src/components/shoppingCart/Plantillas.jsx

fix(plantillas.jsx) fix styles

---

src/Redux/actions.js
src/components/Detail/Detail.jsx
src/components/ForgotPassword/ForgotPassword.jsx
src/components/Nav/Nav.jsx
src/components/Profile/Profile.jsx
src/components/ResetPassword/ResetPassword.jsx
src/components/loginComponents/loginComponents.jsx
src/components/registerComponents/registerComponents.jsx

- Alerts added to Detail - ForgotPassword - ResetPassword
- Alerts were modified to RegisterComponets - LoginComponents - Nav/LogOut - Reduce/Action
- The eye to hide password was modified

feature Alerts

---

.env
package-lock.json
package.json
src/components/Footer/Footer.jsx
src/components/shoppingCart/ComponentShop.jsx

Onclose button fix for closing the form.
Fix in the form so that it is controlled in the state and the form is sent correctly with its corresponding alert.

Fix formFooter

---

src/components/Detail/Detail.jsx

Changes on Detail component

---

src/components/Profile/Profile.jsx

Alert change

---

src/App.js
src/components/Footer/Footer.jsx
src/components/shoppingCart/Plantillas.jsx

You can add/remove templates from the shop.
I add quality labels to templates.
The button changes depending on the status of cart/redux.

add feature shop

---

src/components/Pay/payComponent.jsx

feature payComponent form 
fix payComponent styles

feature(payComponents.jsx) feature paycomponents form and fix styles

---

public/index.html
src/components/DarkMode/darkmode.jsx
src/components/Nav/Nav.jsx
src/styles/output.css
tailwind.config.js

Dark mode component created.
I need to add a class dark in Tailwind.config.
Renderice darkmode on Nav component.

Dark Mode created

---

src/components/PresetsDesigns/Basic/Home/BasicHome02.jsx

feature(basic/home) created a new template

---

src/components/PresetsDesigns/Premium/Detail/PremiumDetail1.jsx

Premium Detail Preset created.-

Premium Detail Preset

---

src/components/Cart/cart.jsx
src/components/DarkMode/darkmode.jsx
src/components/Footer/Footer.jsx
src/components/Home/HomeComponent.jsx
src/components/Nav/Nav.jsx
src/components/Pay/payComponent.jsx
src/components/loginComponents/loginComponents.jsx
src/components/shoppingCart/ComponentShop.jsx
src/components/shoppingCart/Order.jsx

Colors modifications on many components so we can see how darkMode works.

Dark mode styles modifications

---

src/App.js
src/components/ForgotPassword/ForgotPassword.jsx
src/components/ResetPassword/ResetPassword.jsx
src/components/ResetPassword/validation.js
src/components/loginComponents/loginComponents.jsx

Now forgot and reset are completly functional and added styles.

fixed(forgot & reset):

---

src/Redux/actions.js
src/Redux/reducer.js
src/Redux/types.js
src/components/PresetsDesigns/Basic/Home/BasicHome02.jsx
src/utils/ColorPanel.jsx

created  setColor pannel but isn't finish yer

feature(PresetsDesigns/Home/BasicHome02.jsx) created  setColor pannel

---

src/components/shoppingCart/Plantillas.jsx

- Add Card's border
- Fix Card's size
- Add Card's shadow

fix(Plantillas.jsx) fix style

---

src/styles/input.css
src/styles/output.css
tailwind.config.js

config(tailwind) config font

---

src/Redux/actions.js
src/components/Cart/cart.jsx
src/components/Pay/payComponent.jsx

* fix Template's images
* fix bug in pay component

fix(cart.jsx & pay.jsx) fix styles, add Presets's image

---

src/components/shoppingCart/ComponentShop.jsx
src/components/shoppingCart/typesAndColors.jsx
src/utils/img/ulisesPresets.json

fix shop types, colors and json presetsUlises

fix types, colors and json presetsUlises

---

src/Redux/actions.js
src/components/Cart/cart.jsx
src/components/Home/HomeComponent.jsx
src/components/Pay/payComponent.jsx
src/components/shoppingCart/Plantillas.jsx

Many changes

---

package-lock.json
package.json
src/components/Footer/Footer.jsx
src/components/Pay/payComponent.jsx

* fix form's style in Footer.jsx
* fix form's style in PayComponent.jsx

fix(footer.jsx & payComponent.jsx) resolved Tom's tocs

---

src/App.js
src/components/Detail/Detail.jsx
src/components/PreviewPresets/previewPresets.jsx
src/views/previewPresets/previewPresets.jsx

IMPORTANT
Add button in the detail that takes you to the preview of the selected template.
For correct operation YES OR YES, the templates must be loaded as they are in the presetsUlises json

add views presets

---

package-lock.json
src/components/loginComponents/loginComponents.jsx
src/components/registerComponents/registerComponents.jsx

Login Route

---

src/components/PresetsDesigns/Medium/Shop/MediumShop.jsx
src/components/PreviewPresets/previewPresets.jsx
src/components/loginComponents/loginComponents.jsx

created a preset medium shop, pending to improve

created a preset medium shop, pending to improve

---

src/components/AboutPage/people.jsx
src/components/PreviewPresets/previewPresets.jsx
src/utils/img/ulisesPresets.json

Add pictures about.
Add name's Presets.

add pictures About and name's Presets

---

package-lock.json
src/components/Nav/Nav.jsx

Fix toogle navigation.
Alignment of components in navigation bar.
Removal of team navigate
Incorporation of components to the navigation toogle

Fix Toogle Navigate

---

public/index.html
src/components/PresetsDesigns/Basic/Home/BasicHome02.jsx
src/components/PresetsDesigns/Premium/Home/PremiumHome01.jsx

* Fix bug in BasicHome02.jsx
* Created PremiumHome01.jsx
* Add in public/html google font's link

New templates

---

src/components/Purchases/purchases.jsx

Route for GET request of purchases changed(It is necessary to separate the purchase request by email and all purchases)

Fix(RoutePurchase): Route for GET request of purchases changed

---

package-lock.json
src/App.js

The login token handling was refactored and now auth0's users is logged out correctly when the token expires.

fixed(app): auth0 login

---

src/Redux/actions.js
src/Redux/reducer.js
src/Redux/types.js
src/components/PreviewPresets/previewPresets.jsx
src/components/shoppingCart/Pagination.jsx
src/components/shoppingCart/Plantillas.jsx
src/utils/img/ulisesPresets.json

I add names to the new templates created and add them to the json and its corresponding preview.
I add pagination in the shop.

add pagination in shop  and name/json/preview presets new's

---

src/components/PresetsDesigns/Premium/Cart/PremiumCart01.jsx

Created a new Preset: Premium Cart

Premium Cart Preset

---

src/components/Cart/cart.jsx
src/components/DarkMode/darkmode.jsx

Moved the dark/light mode icon

Style Changes on DarkMode component

---

src/components/PreviewPresets/previewPresets.jsx
src/utils/img/ulisesPresets.json

Presets and Json

---

src/utils/img/ulisesPresets.json

Presets img

---

src/components/Home/HomeComponent.jsx
src/utils/ColorPanel.jsx

* Add images to Carousel
* Add comments
* Remove back icon

fix(Home.jsx) add images to carousel(hardcode)  and add comments

---

src/components/Nav/Nav.jsx

fix(Nav.jsx) fix position's bugs

---

src/components/Home/HomeComponent.jsx

Change preset url on Home component

Change preset url on Home component

---

src/components/Cart/cart.jsx

Other changes on cart component

Cart component

---

src/components/Nav/Nav.jsx
src/components/Purchases/purchases.jsx

fix(Purchases.jsx & Nav.jsx) fix stile

---

src/App.css
src/App.js
src/components/Cart/cart.jsx
src/components/shoppingCart/ComponentShop.jsx

Changed styles for all scrollbars
Fixed background of shops not displaying the correct colors on low definitions

Fixed styles
